### ISSUE TITLE
Unable to create class

### ISSUE THREAD

**Issue by pavelaizen** [t28hub/json2java4idea#130]
Hello, I'm trying to create class for following json:
{
    "today_data": {
        "current_date": "07/02/2017",
        "start": 23,
        "end": -99,
        "start_w": "5",
        "end_w": -99,
        "code": "SF",
        "ccd": 5,
        "cfp": "f",
        "sick": 0
    },
    "monthly_data": {
        "2016-02": {
            "cdays": "28,29,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,21,22,23,24,25,26",
            "f_phases": "l,2,3,4,5"
        },
        "2016-03": {
            "cdays": "28,29,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,21,22,23,24,25,26",
            "f_phases": "l,2,3,4,5"
        },
        "2016-04": {
            "cdays": "28,29,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,21,22,23,24,25,26",
            "f_phases": "l,2,3,4,5"
        }
    }
}

Why ?

**Comment by pavelaizen** [comment]
Even tried with a short version"

{
    "today_data": {
        "current_date": "07/02/2017",
        "start": 23,
        "end": -99,
        "start_w": "5",
        "end_w": -99,
        "code": "SF",
        "ccd": 5,
        "cfp": "f",
        "sick": 0
    },
    "monthly_data": {
        "2016-02": {
            "cdays": "28,29,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,21,22,23,24,25,26",
            "f_phases": "l,2,3,4,5"
        }
    }
}
No error, class was not created

**Comment by t28hub** [comment]
@pavelaizen 
Thank you for reporting your issue.
The reason why a class was not generated from the JSON is that this plugin could not convert class name from fields named `2016-02`, `2016-03` and `2016-04`.
As you might know, Java does not support class name started with numbers.
This plugin would have tried to create a class named `201602`.
I will try to fix it ASAP.
Sorry for inconvenience.
