### ISSUE TITLE
The plugin makes `preferences` frozens the UI in 2017.2

### ISSUE THREAD

**Issue by aristotll** [t28hub/json2java4idea#142]
My problem is described in https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000469430-After-updating-to-2017-2-clicking-preference-or-pressing-command-cause-the-UI-to-freeze-

I have to debug into the idea, and I find it is because of `io.t28.json2java.idea.setting.Json2JavaConfigurable`.

The self reference causes the infinite loop.
The `myParent` is same as itself.

**Comment by CrazyCoder** [comment]
See also https://youtrack.jetbrains.com/issue/IDEA-176137.

**Comment by aristotll** [comment]
![2017-07-19 23 12 23](https://user-images.githubusercontent.com/13341544/28375845-330c36c2-6cdb-11e7-8925-e86545eab617.png)

**Comment by t28hub** [comment]
@aristotll 
Sorry for inconvenience.
This bug has been fixed in #143.
I'm planning on publishing stable plugin ASAP.

**Comment by t28hub** [comment]
This changes was released at [0.2.2](https://plugins.jetbrains.com/plugin/9577-json2java4idea/update/37075).
